### ISSUE TITLE
Media HueBot on Service Fabric (SF) cluster environment?

### ISSUE THREAD

**Issue by oleksii-gudz** [microsoftgraph/microsoft-graph-comms-samples#123]
I have switch my local Service Fabrics to work in 5-node mode, change Local.5node.xml config file to have HueBot_TargetReplicaSetSize=2 and tried to launch HueBot sample app. Obviously it failed with exception "There is already a listener on IP endpoint 0.0.0.0:8445. This could happen..." while initializing media platform.

![image](https://user-images.githubusercontent.com/13114542/68590062-4d7f1100-0496-11ea-9578-c219ba6d7b2a.png)

It is clear that our second Bot instance tried to use the same port for media platform, but how it should correctly behave in SF cluster? Does SF have out of the box load balancer for such use cases or we need our own?
How can I make it work on cluster with more than 1 active replica?
And in general do we have an option to run more than 1 instance of media bot on 1 physical machine/VM?
Thanks in advance!

**Comment by ksikorsk** [comment]
In the SF cluster there is 1 partition per node, so each node can have the port 8445 reserved.  This does not work locally because you have 5 partitions per node (your local machine).  The HueBot sample **does not support 5 node local runs**.

It is important that the media platform is configured to have 1 process per VM (1 partition per node).  Internally it does thread optimization which does not work well with multiple media platforms running.  This also means that the media platform does not support replicas.  If you look at the sample  you'll notice that the partition count == node count, this is not by accident.

https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/15b8070a5b65ee0829823bbd7d0fa5d527ba8879/Samples/V1.0Samples/LocalMediaSamples/HueBot/HueBotSF/ApplicationParameters/Cloud.xml#L4-L6

Even if the media platform did support replicas, there is no way today to revive a media session.  The recommended way of recovering a dead call is to do a dial out, or rejoin (using the `ChatInfo` and `MeetingInfo` provided in the `call`)

**Comment by ksikorsk** [comment]
@ssulzer can add more detail why only a single instance of the MP should run on a given VM.

**Comment by oleksii-gudz** [comment]
Great, thanks!
So if I will create SF cluster that consists of 5 nodes (separate VMs that have public ips), media Huebot will be able to launch its instances on all of them. But still it is not clear how it will work during the call? If I understand correctly in this case we should have load balancer with own custom logic that would route new call notifications to free nodes and established call notifications to same nodes. Please correct me if I am wrong.
Any recommendations in this area?

Thanks!

**Comment by ksikorsk** [comment]
SF comes with a software LB when addressing the cluster.  That is only required for the initial call setup.  After the call has been set up you configure a callback URI and an MP host/port and the call becomes sticky with the given VM.

**Comment by ksikorsk** [comment]
Also, while having a public IP for each VM is recommended, it is possible to do this with only one public IP.  You can specify an external port and an internal port.  The SF reverse proxy is able to map to the right instance/port.  The downside of this is that you introduce an extra hop, which is not ideal for media flow.

**Comment by oleksii-gudz** [comment]
> After the call has been set up you configure a callback URI and an MP host/port

do you mean this part of sample?

`builder.SetNotificationUrl(options.BotBaseUrl.ReplacePort(options.BotBaseUrl.Port + 
 serviceContext.NodeInstance()));`
`builder.SetMediaPlatformSettings(this.MediaInit(options, serviceContext));`

**Comment by ksikorsk** [comment]
Yes, that's right. In MediaInit you'll see configuration of public and internal ports:

https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/15b8070a5b65ee0829823bbd7d0fa5d527ba8879/Samples/V1.0Samples/LocalMediaSamples/HueBot/HueBot/Bot/Bot.cs#L337-L344

Internal port is always 8445, and public port will be 8445 + instance number

https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/e7755438737274c00d0081e9b1d8a3c8fc5eb42b/Samples/V1.0Samples/LocalMediaSamples/HueBot/HueBot/appsettings.json#L14

**Comment by oleksii-gudz** [comment]
Do we need to make any manipulations to enable stickiness on SF balancer? By the way do you know how does it work? Does it work by sender ip,  X-Microsoft-Skype-Chain-Id header, etc?
Also does SF balancer have possibility to route new calls to nodes that have lower load than others? If no, do you know how such scenario can be supported?

Many thanks!

**Comment by ksikorsk** [comment]
No manipulations needed.  It works by port.  If the cluster port is specified, it will direct to the cluster.  If a partition port is specified it will direct to the partition.  The ARM deployment script configures the NAT pools:

https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/15b8070a5b65ee0829823bbd7d0fa5d527ba8879/Samples/V1.0Samples/LocalMediaSamples/HueBot/HueBot/ARM_Deployment/AzureDeploy.json#L206-L208

I believe you can configure the SF LB, but I am not sure how.  BTW, it is dangerous to route new calls to nodes with lower load.  Consider a faulty node, where all calls routed to it are terminated immediately.  It will have low load, which will result in disproportionate % of calls being sent there and killed.  Round robin is safer.  If you really want to go advanced you can have partition groups, and an LB that directs traffic to the partition group with lowest load.  I don't know how you could achieve such a configuration in SF.

**Comment by oleksii-gudz** [comment]
> No manipulations needed. It works by port.

Not sure I understand how it works. In the Azure portal we are setting signalling web hook for calls. In our case it is going to be cluster alias.


![image](https://user-images.githubusercontent.com/13114542/68865666-e06cb500-06fb-11ea-8d9b-be6a43d54c50.png)


And AFAIU media platform will use it for sending notifications. How we will achieve stickiness by port in this case? Does media platform differentiate node from which it get the response?

Thanks!

**Comment by ksikorsk** [comment]
Running locally is different than running in Azure.  Local runs only have 1 instance, so all you need to do is redirect the signaling http traffic to your open signaling port (9441 I think?)  and media tcp traffic to your open media port (8445).  Ngrok does this for you.  Because local runs are only 1 instance, the global URI can be the same as the instance specific URI, and the global media port is the same as the instance specific port.

In azure, there global callback URI is your cluster URI, and when hit it will distribute the request to one of your partitions.  After that all traffic must be sticky to that partition for the remainder of the call.  Each partition knows it's own media and signaling ports, and specifies them in the `ICommunicationsClientBuilder.SetNotificationUrl` and the `MediaPlatformSettings`.  These new settings get used to notify the bot of any changes for that call, and allow the media to flow.

**Comment by oleksii-gudz** [comment]
Thanks a lot, Kamil, for your answers!
