### ISSUE TITLE
Does Graph Communications Calling SDK support non-Azure envrionment

### ISSUE THREAD

**Issue by hohno-panopto** [microsoftgraph/microsoft-graph-comms-samples#143]
Does Graph Communications Calling SDK have any specific dependency to Azure environment?
Or, is it supposed to work on any Windows server, as far as it is accessible from the Internet?

**Comment by ksikorsk** [comment]
Microsoft.Graph.Communications.Calling SDKs have no dependencies on Azure... any environment that supports .NET core/.NET framework will work.  The one requirement is that each instance of an ICall can be uniquely addressable since the Calling SDK is a stateful SDK.

Microsoft.Skype.Bots.Media SDK is required to be on Azure on a windows VM.  We have a Cloud Service sample and a Service Fabric sample.

**Comment by hohno-panopto** [comment]
Thank you for the reply. w.r.t. Bot Media SDK, which one of these is correct?
1. Bot with Media handling capability may run only on Azure by its system design/spec.
2. Bot with Media handling capability might run outside of Azure, but that API/spec is not public.
3. Bot with Mead handling capability may run outside of Azure based on public API/spec.

If the answer is number 3, I would also know:
a. Where is the API doc / spec about it?
b. Is it on the roadmap of Bot Media SDK to support non-Azure envrionment?

**Comment by ksikorsk** [comment]
I believe the answer is 2)  @ssulzer can confirm.  He can also provide details on any roadmap for "Bot Media SDK to support non-Azure envrionment".

**Comment by ssulzer** [comment]
Bots using the Microsoft.Skype.Bots.Media API must run in Azure. There is no roadmap to support non-Azure runtime environments.

**Comment by hohno-panopto** [comment]
Thank you for the clarification.
