### ISSUE TITLE
[CompliantRecordingBot] Media sockets

### ISSUE THREAD

**Issue by hohno-panopto** [microsoftgraph/microsoft-graph-comms-samples#151]
- The sample sets up 1 audio socket. Is it true that Bot receives always just a single audio stream that has all audio sources muxed?
- The sample sets up  3 video sockets. Is this a limitation of Graph communication media platform? Or, is it just an arbitral number and a bot may subscribe as many videos as it likes?
- As far as I tested, video size is not fixed even though we pass VideoResolution.HD1080p to Subscribe() method. It is different based on captured region, as well as initial few frames are typically smaller than later frames in stable state. Is this a known limitation (design) and the bot code needs to handle such different frame sizes in a single video stream?
- The sample sets up 1 VBSS socket. Is it true that single meeting has up to 1 shared screen at any one time?
- IDataSocket seems to be defined for transcription (Enum DataType.Transcript). Is this stream available now or will it be available in the near future as beta feature?

**Comment by ksikorsk** [comment]
@ssulzer can help here.

**Comment by ssulzer** [comment]
@hohno-panopto 

- Audio: by default the bot receives an audio stream containing a mix of the current speakers (if more than one participant is speaking). This audio stream includes metadata for the bot to identify what audio sources (Media Source IDs) it is hearing in the mix in each received audio buffer.
There is also an option to switch to unmixed mode (using the ReceiveUnmixedMeetingAudio option - https://microsoftgraph.github.io/microsoft-graph-comms-samples/docs/bot_media/Microsoft.Skype.Bots.Media.AudioSocketSettings.html#properties).  This allows the bot to receive separate frames of audio from each speaker rather than a single frame with the mix. However, it is important to note that the unmixed audio mode is optimized for machine cognition (e.g., transcription) rather than for recording for human listening. In unmixed mode, the platform disables certain error concealment treatments of the audio stream (such as stretching/interpolating if there are missing audio packets, as such healing processes do not add any useful content that would aid speech recognition). Since both the bot and the Teams conference server are running in Azure, packet loss should be minimal, but if there is a burst of packet loss it may be noticeable if you record (and then play back) the unmixed audio stream.

- # of Video Sockets: for the "main-video" modality, a bot may have a maximum of 10 VideoSocket objects in a single conference join session (i.e., per bot call). Each VideoSocket may be subscribed to a different video source in the meeting, so a single bot could receive the video of 10 different participants concurrently.

- Resolution/framerate of received video may not match what the bot requested in its VideoSocket.Subscribe API call, and the received format may change dynamically: this is by-design. There are many factors which impact what resolution/format will be received: such as the (possibly changing) bandwidth conditions and capabilities of the video source endpoint, and also what other participants within the conference are asking for in their video subscription requests. The Teams conferencing server takes all of these varying conditions into account in deciding how best to deliver the video sources to the viewers.

- # of VBSS sockets: a bot may have at most 1 VideoSocket for the VBSS modality per bot call. Within a Teams meeting there can be only one VBSS content sharer at a time. 

- IDataSocket: this API is not available for use for any purpose; currently we do not have anything to say about it.

Hope that helps. Thanks.

**Comment by hohno-panopto** [comment]
@ssulzer Thank you very much for explaining the details. It's really helpful for me to design my bots. It is so perfect that I cannot think of any follow up 👍

**Comment by pavanjains** [comment]
@ssulzer Above explanation is great, I had these follow up questions

1. When I make VideoSocket to 1 is there a way to request Active speaker video just like Audio is mixed on one socket? Current implementation requires subscribing and unsubscribing 

2. Can we request MS teams to sends a thumbnail video if participant video is off?
