### ISSUE TITLE
[CompliantRecordingBot] CallHandler.OnRecordingStatusFlip()

### ISSUE THREAD

**Issue by hohno-panopto** [microsoftgraph/microsoft-graph-comms-samples#152]
I understand that this method intends to demonstrate the operation that Media Bot may stop the recording in the middle of the call/meeting. However, I do not understand other operations, i.e. setting the status to 'RecordingStatsu.Failed' or calling IParticipant.DeleteAsync(). What kind of real world scenarios do they try to simulate? I don't see ICall.UpdateReocrdingStatusAsync(), and do you plan to add this to the doc by the next update?

**Comment by ksikorsk** [comment]
`ICall.UpdateReocrdingStatusAsync()` is only in `beta`, so no documentation yet.  All it does is send a signal to the Teams client, which would then draw up some UI that tells users what is happening.  I believe the Teams client changes have rolled out, so you can try and test it out and see what happens when you set the different states.

https://docs.microsoft.com/en-us/graph/api/call-updaterecordingstatus?view=graph-rest-beta&tabs=http

The `Started` state must be reported for by bots recording the call (while they are recording), and is a requirement to use the Compliance Recording APIs.  If we find any bots not conforming to this requirement, we will disable them.

The `Failed` state is required for compliance for reporting purposes, and it is recommended that if anything goes wrong the bot, it should send this state.

`IParticipant.DeleteAsync()` allows the bot to _remove only the Recorded Participant (RP)_ from the call.  This is to support policy evaluations.  One example is if an RP can only be in a call with other compliant users, and if anyone joins that is non-compliant the bot can eject the RP.

Consider the APIs exposed as a toolbox to allow the bot to perform various Compliance Recording related activities.  Your bot may not have a need for these, but others may.

**Comment by hohno-panopto** [comment]
Thank you for the explanation.
That totally makes sense.
The good news is that I observed correctly that Teams client UI showed the banner for it!
![Screen Shot 2020-01-13 at 9 20 26 AM](https://user-images.githubusercontent.com/8325283/72276983-f4427380-35e5-11ea-9124-177a036646a5.png)

Let me ask two follow up questions.

1. Am I correct that media feed to the bot starts and ends unrelated to this method? i.e. this method does not directly affect the timing of media streaming?

2. You said 'reporting purpose'. Am I correct that Teams will have (or already has) the capability to record this call and report it to Tenant admin?

**Comment by ksikorsk** [comment]
1) yes
2) That would be a PM question, I am not sure.

**Comment by hohno-panopto** [comment]
Thank you! I will find out someone who may answer #2 via our business channel.

**Comment by jsweiler** [comment]
> The Started state must be reported for by bots recording the call (while they are recording), and is a requirement to use the Compliance Recording APIs. If we find any bots not conforming to this requirement, we will disable them.

@ksikorsk What is meant by "while they are recording"? Does that mean only when I have subscribed to the `AudioSocket.AudioMediaReceived` event or subcribed to video, or does it mean any time the compliance recording bot is in a call.

Basically I am wondering if I have our compliance recording bot in the call and it is not subscribing to any media do I still have to show the `Started` status message?

**Comment by ksikorsk** [comment]
It means any time the bot is persisting the AV data (storing it).  It could be streaming and in the call, but not persisting the data.  That is technically `NotRecording`
