### ISSUE TITLE
Recorded user does not get the call

### ISSUE THREAD

**Issue by stefan2410** [microsoftgraph/microsoft-graph-comms-samples#205]
I debug  the RecordingBot locally and I can see from the logs that the Bot gets all messages from the incoming  call and media are prepared.
 But  the call never rings to the recorded user. What I'm doing wrong?

**Comment by stefan2410** [comment]
For one call, during the 20 seconds, default ringing,
I get 2 incoming  (I think, they are the  2 legs , caller and callee, right?) 
and 2 notifications for each leg  "establishing" and "terminated"
In case,  I would listen the voicemail,  I  would get another one notification "terminated".
Is it the normal behavior?
What could be a possible reason that the recorded user does not get the call at all ?
I call from a non recorded user  (he was recorded before but I revoked it with PolicyName $null

**Comment by ssulzer** [comment]
@zhengni-msft

**Comment by ssulzer** [comment]
Hi @stefan2410 

The calls failed because our platform services could not connect to the bot's media SDK at "bot.<your-bot-service-domain-name>.com:13223":
System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 52.170.56.121:13223

Attempts to connect to this address failed both from our platform cloud services as well as locally from within the bot media SDK itself.

Can you please double check that we are getting the right IP address for your bot service DNS, and whether 13223 is the right port. Thanks.

**Comment by stefan2410** [comment]
@ssulzer  thank you 
we changed in AzureConfigurion.cs  the ports
  
            //int mediaInstanceInternalPort = RoleEnvironment.IsEmulated ? 8445 : mediaControlEndpoint.IPEndpoint.Port;
            //int mediaInstancePublicPort = RoleEnvironment.IsEmulated ? 13223 : mediaControlEndpoint.PublicIPEndpoint.Port;

            int mediaInstanceInternalPort = RoleEnvironment.IsEmulated ? 20200 : mediaControlEndpoint.IPEndpoint.Port;
            int mediaInstancePublicPort = RoleEnvironment.IsEmulated ? 8446 : mediaControlEndpoint.PublicIPEndpoint.Port;

  and  

             netsh interface portproxy add v4tov4 listenport=8446 connectaddress=127.0.0.1 connectport=20200 protocol=tcp

and it worked.

**Comment by ssulzer** [comment]
Good to hear! Thanks.
