### ISSUE TITLE
Capture RTMP feed from Live Even with Application-Hosted Media Bot.

### ISSUE THREAD

**Issue by pagella42** [microsoftgraph/microsoft-graph-comms-samples#233]
Hey, i am trying to build a bot that could capture the stream from a live event, but i'm encountering a problem when the feed comes from an RTMP stream  from an external encoder; In this case the bot is not able to capture it.

Any suggestions?

**Comment by ssulzer** [comment]
There is no support in the Graph Communications/Microsoft.Skype.Bots.Media bot platform for receiving a media feed via RTMP.

**Comment by jrebagliatti** [comment]
Hey @ssulzer I'm also trying to understand if it's possible to join a calling bot to a Live Event **produced using an an external encoder**. 
It seems that under that configuration, the live event is leveraging the Microsoft Stream infrastructure, instead of Teams/Skype's, to handle the call, and for that reason the bot is unable to join, or capture the stream. 
Could you confirm is my assumption is correct? Thanks!

**Comment by ssulzer** [comment]
@jrebagliatti  That's correct.

**Comment by jrebagliatti** [comment]
Thanks @ssulzer. Do you know if supporting this use case is the future plans?

**Comment by ssulzer** [comment]
Follow-up discussion here: https://github.com/microsoftgraph/microsoft-graph-comms-samples/issues/221#issuecomment-628824077

**Comment by pagella42** [comment]
@ssulzer We could finally do this following your recommendations, and we are getting the producer feed.

Now we are having a problem, when trying to differentiate whether our bot is joining a regular call or if it is a Live Event. Is there an actual way to do this by this time? Could you please guide us on how?

Any help will be appreciated, 
Thanks
