### ISSUE TITLE
Participants not updated

### ISSUE THREAD

**Issue by stefan2410** [microsoftgraph/microsoft-graph-comms-samples#236]
Last days, the event Participants.Updated is not raised from the Client.
I've a multitenant application, but even if I create only one Client,  I don't get the event.
graph API v1.0
Communications.Client 1.2.0.850
I don't know if it helps you to check the callId "f21f0200-b31f-4cbb-b1bf-64bb0f3be6e8"

**Comment by ssulzer** [comment]
@zhengni-msft

**Comment by stefan2410** [comment]
@ssulzer The event  Participants.Updated, still, is not raised from the Client.
I wanted to ask you something else by the way. What it is better, to create different clients ( with their stack) and the  same media platform? or to create also different media platforms listening in different ports?  My guess is for the same media platform, as it will utilize better th VCPUs.

**Comment by ssulzer** [comment]
@stefan2410 
Someone from @zhengni-msft's team is looking into the Participants.Updated question.

I am not sure about your other question, but within a single operating system process or Cloud Service worker role instance, you should have just one MediaPlatform instance running. Your service can host multiple different bot apps on the same MediaPlatform instance, if you want.

**Comment by stefan2410** [comment]
@ssulzer thank you.
That exactly what I'm doing, one MediaPlatform instance running in worker role.

**Comment by jackry6350** [comment]
Hi @stefan2410 , I checked the call you mentioned. Platform service actually sent the participant update notification to your bot, but got 401 Unauthorized error. Typically it should be caused by certificate issue, so that your bot didn't trust the notification that Platform service sending.
Can you follow this doc and double check whether the certificate was uploaded and valid.
[https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples/V1.0Samples/LocalMediaSamples/AudioVideoPlaybackBot#azure-deployment](url)

BTW, I do see some notifications got 202 response, while some others got 401. Either you have different instances running and the certificate was configured differently for them, or your bot code logic sent the 401 in some of the cases.

**Comment by stefan2410** [comment]
Hi @jackry6350  I'll read the doc, only to inform you that I got the notifications for the participants till previous week.  I'm not sure about  the time I updated the client from .791 to .850.  Maybe it was in the weekend. 
I've started also running multiple clients concurrently  with different tenants.. Everything works fine, with multiple tenants,  except the Participants.Updated.  Even if I had enabled only one client, again I have the problem.
I'll look about the certificate. Should I set in ServiceConfiguration  all the certificate thumbprints? 
I've only one right now (but it was common I think for the first 2 tenants and I had the problem with the event. Maybe it is not common for a third one tenant, added today)
Is there a way to  provide the  thumbprint to AuthenticationProvider. programmatically ?
