### ISSUE TITLE
How does the audio route in AKS sample ?

### ISSUE THREAD

**Issue by vonguyen1982** [microsoftgraph/microsoft-graph-comms-samples#384]
I have a look at the AKS sample for bot recording and I could not understand how the audio will get to the pod(bot).
I could see the settings below
AzureSettings__InstancePublicPort=RESERVED_PORT ## TCP
AzureSettings__CallSignalingPort=LOCALHOST_HTTP_PORT ## 9441
AzureSettings__InstanceInternalPort=LOCALHOST_TCP_PORT ## 8445
They are TCP ports for signaling and media server. The audio does not go to that port. The audio is using UDP port.
Also the requirement of public IP address does not change that means each pod need to have a public IP address ? so how come could we have 2 pods in same VM or node ?

**Comment by JasonTheDeveloper** [comment]
Hey @vonguyen1982,

We do have a doc detailing how the AKS sample works in [docs/deploy/aks.md](https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/master/Samples/V1.0Samples/AksSamples/teams-recording-bot/docs/deploy/aks.md#concept-how-bot-works-in-kubernetes). 

Looking at that doc you will find the following diagram:

![aks](https://raw.githubusercontent.com/microsoftgraph/microsoft-graph-comms-samples/master/Samples/V1.0Samples/AksSamples/teams-recording-bot/docs/images/k8s.png)

Referring to the diagram, you will see a SVC icon labeled `LoadBalancer` sitting inside the `ingress-nginx` namespace to the left. This in the entry point to the cluster and has a range of ports open to allow HTTP traffic and media to flow through to our pods. 

This is where the public IP address sits. There's only one public IP address needed and can be set using [public.ip](https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/master/Samples/V1.0Samples/AksSamples/teams-recording-bot/deploy/teams-recording-bot/values.yaml#L29) when deploying the bot using the Helm chart. This IP address is what you'll map your domain to so cert-manager can create your SSL certificate, the domain you would have used when setting up your [Bot Channel Registration](https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/master/Samples/V1.0Samples/AksSamples/teams-recording-bot/docs/setup/bot.md) and is something you'll need to setup separately. When you deploy the bot, you'll need to set this domain using [host](https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/master/Samples/V1.0Samples/AksSamples/teams-recording-bot/deploy/teams-recording-bot/values.yaml#L9). The bot uses that domain in a number of places but is basically used to tell Teams where to [send media traffic to](https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/master/Samples/V1.0Samples/AksSamples/teams-recording-bot/src/RecordingBot.Services/ServiceSetup/AzureSettings.cs#L217). This value is read in from `AzureSettings__ServiceDnsName`.

In terms of how audio flows to the pods, each pod that's deployed basically has their own dedicated port on the [LoadBalancer](https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/master/Samples/V1.0Samples/AksSamples/teams-recording-bot/deploy/teams-recording-bot/templates/external.yaml#L24-L29) as mentioned above ([more info](https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/master/Samples/V1.0Samples/AksSamples/teams-recording-bot/docs/deploy/aks.md#external-load-balance)). Each pod has their own dedicated [service](https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/master/Samples/V1.0Samples/AksSamples/teams-recording-bot/deploy/teams-recording-bot/templates/service.yaml) (the SVC icons labeled as `Media` in the diagram - [more info](https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/master/Samples/V1.0Samples/AksSamples/teams-recording-bot/docs/deploy/aks.md#clusterip-service)) and using NGINX, we have a [configmap](https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/master/Samples/V1.0Samples/AksSamples/teams-recording-bot/deploy/teams-recording-bot/templates/configmap.yaml#L14-L16) (see `TCP Pod Port Mapping` in the diagram - [more info](https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/master/Samples/V1.0Samples/AksSamples/teams-recording-bot/docs/deploy/aks.md#configmap)) to map the external ports to the corresponding services.

When you set `AzureSettings__InstancePublicPort`, you're telling Teams which port to [send media](https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/master/Samples/V1.0Samples/AksSamples/teams-recording-bot/src/RecordingBot.Services/ServiceSetup/AzureSettings.cs#L216). This port is exposed to the public on the external loadbalancer as mentioned [here](https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/master/Samples/V1.0Samples/AksSamples/teams-recording-bot/docs/deploy/aks.md#external-load-balance). 

`AzureSettings__InstanceInternalPort` instructs the bot which port to listen to for media. This value is used by the media services mentioned above (the SVC icons labeled as `Media` in the diagram).

So looking at the diagram above, where you see that green arrows, those represent the flow of audio from Teams to the bot.

I think where the confusion might be is where it says `TCP` when referring to the flow of audio. I think the reason why the documentation says `TCP` over `UDP` is because the ports that we open on the [loadbalacer](https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/master/Samples/V1.0Samples/AksSamples/teams-recording-bot/deploy/teams-recording-bot/templates/external.yaml#L28) to allow audio to flow is using the `TCP` protocol. I might update the docs to make that a little more clear. 

I hope that answers your question.

**Comment by vonguyen1982** [comment]
@JasonTheDeveloper : Thank you very much for explanations very details.   

In the AzureConfiuration (https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/master/Samples/V1.0Samples/LocalMediaSamples/PolicyRecordingBot/WorkerRole/AzureConfiguration.cs)

                MediaPlatformInstanceSettings = new MediaPlatformInstanceSettings()
                {
                    CertificateThumbprint = defaultCertificate.Thumbprint,
                    InstanceInternalPort = mediaInstanceInternalPort,
                    InstancePublicIPAddress = publicInstanceIpAddress,
                    InstancePublicPort = mediaInstancePublicPort,
                    ServiceFqdn = serviceFqdn,
                }

By default I think MediaPortRange is from 48K to 65K if not specify. With AKS do we still use that MediaPortRange ? if Yes then how the UDP mapping from loadbalancer  to pod because all pods will have the same MediaPortRange (48k to 65K).  I did not see any where mention about mapping MediaPortRange. We only mapping TCP port which I think only using for connection handshaking not for audio transfer. The MediaPortRange is the UDP port for bot received audio packet. Am I correct ?

**Comment by JasonTheDeveloper** [comment]
@vonguyen1982 I'm not too familiar with how the `MediaPortRange` works, if I'm being completely honest. Someone from the graph team will need to answer that. From my understanding though, the `MediaPortRange` specifies the range of ports Teams can send media through to the bot. This could be port 3000 to 4000, for example. 

`MediaPortRange` is optional however, as specified in [MediaPlatformInstanceSettings](https://microsoftgraph.github.io/microsoft-graph-comms-samples/docs/bot_media/Microsoft.Skype.Bots.Media.MediaPlatformInstanceSettings.html#Microsoft_Skype_Bots_Media_MediaPlatformInstanceSettings_MediaPortRange). From the AKS sample stand point though, you're right in that we're not specify the `MediaPortRange`. We don't specify the port range because we have a dedicated port for each pod deployed, meaning each pod listens to just one port. That port is specified by setting [InstancePublicPort](https://microsoftgraph.github.io/microsoft-graph-comms-samples/docs/bot_media/Microsoft.Skype.Bots.Media.MediaPlatformInstanceSettings.html#Microsoft_Skype_Bots_Media_MediaPlatformInstanceSettings_InstancePublicPort).

Have you tried deploying the sample?

**Comment by vonguyen1982** [comment]
Thanks for clarify. I have not tried to deploy it because I am try to find the pros and cons before decided to move forward.

**Comment by vonguyen1982** [comment]
@JasonTheDeveloper : I have a chat with Aditya. The  **InstancePublicPort** mapping to  **InstanceInternalPort** you mentioned is not for receiving audio. Also if you don't specify **MediaPortRange** it still needs UDP ports to receive audio packet. I still believe that we are missing mapping UDP port here :) Do you mind to clarify with your team please? Does the AKS sample work with your development environment and can record audio ?

**Comment by 1fabi0** [comment]
You don't need to specify UDP Port because over the tcp connection the bot gets information about where to connect to receive media and after it received this information the Bot initiates the udp connection towards the endpoint that was specified somwhere in the MediaPlatform TCP messages, I think this MediaPortRange setting is Optional to tell the Microsoft Servers which Port range is open on your firewall for outgoing udp connections, I hope you guys understand what I'm talking about. If not feel free to ask.

**Comment by JasonTheDeveloper** [comment]
@vonguyen1982 - apologies for the late reply but to add to @1fabi0's comment, if you need more info about what's happening under the hood, check out this comment https://github.com/microsoftgraph/microsoft-graph-comms-samples/issues/51#issuecomment-474014222

**Comment by vonguyen1982** [comment]
Thanks
