### ISSUE TITLE
Get audio statistics of a Teams call?

### ISSUE THREAD

**Issue by leo0104** [microsoftgraph/microsoft-graph-comms-samples#520]
Hi!

I'm developing a bot application that uses application-hosted media.
During a Teams call with the Microsoft Teams desktop client i get lots of audio statistics about the call like
- bitrate
- sent codec
- received codec
- sent packets
- received packets

Is it possible to get these call information as a bot?

The only information the bot receives within the [AudioMediaBuffer](https://microsoftgraph.github.io/microsoft-graph-comms-samples/docs/bot_media/Microsoft.Skype.Bots.Media.AudioMediaBuffer.html#properties) are the `RoundTripDelay` and `JitterBufferLength`.

**Comment by 1fabi0** [comment]
Hi.

On the audio socket there is a Method for getting the Quality of Expirenced Data,https://microsoftgraph.github.io/microsoft-graph-comms-samples/docs/bot_media/Microsoft.Skype.Bots.Media.IAudioSocket.html#Microsoft_Skype_Bots_Media_IAudioSocket_GetQualityOfExperienceData that already contains quite a lot what the network is doing and how long, but you probably wont know which codec is used or what bitrates your bot has to handle from this endpoint also because that shouldn't matter for any bot as the bot logic receives and sends pcm audio data, the codec used is probably choosen by the use case like the OPUS codec does with SILK and CELT by analyzing the audio. The official documentation says " It uses codecs such as SILK and G.722 for audio"(see [here](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/real-time-media-concepts)) so with the bot you can't really determin what codec is used by Teams especially since it in theory it could chang mid meeting.
